### ISSUE TITLE
Latest version (2.0.0) of the library: begin() fails with the FRAM breakout board (Product ID: 1895)

### ISSUE THREAD

**Issue by dlveach** [adafruit/Adafruit_FRAM_I2C#22]
- Arduino board:  Nano 33 BLE

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.15

- List the steps to reproduce the problem below 

Brand new (just purchased) Adafruit FRAM I2C breakout board.  Product ID 1895.
Install latest version of the Adafruit_FRAM_I2C library (2.0.0)
Using default I2C address 0x50  (confirmed with I2C_Scanner sketch)
Code fails in Adafruit_FRAM_I2C.cpp call to begin():

Following is code from the 2.0.0 library file Adafruit_FRAM_I2C.cpp.  The attempt to connect with begin() to the secondary address is specifically what fails and returns false.

```
bool Adafruit_FRAM_I2C::begin(uint8_t addr, TwoWire *theWire) {
  Adafruit_EEPROM_I2C::begin(addr, theWire);

  // the MB85 has a secondary address too!
  i2c_dev2 = new Adafruit_I2CDevice(MB85RC_SECONDARY_ADDRESS, theWire);
  if (!i2c_dev2->begin()) {
    return false;
  }
```

I2C_Scanner sketch detected the 0x50 default address however did NOT detect any secondary address.  So it does not appear to be present in this particular FRAM chip.

After downgrading the Adafruit_FRAM_I2C library to ver 1.3.3  everything works fine and the begin() fn returns true as expected.  Version 1.3.3 does not have the attempt to connect to a secondary I2C address.

**Comment by ladyada** [comment]
hi can you format the issue so we can tell where the code starts and begins

**Comment by dlveach** [comment]
Sorry, I broke the markup.   Should be clear now?   Lemme know if you need more.

**Comment by caternuson** [comment]
Can't recreate this easily. Connected an I2C FRAM breakout ([PID 1895](https://www.adafruit.com/product/1895)) to an Itsy nRF52840 ([PID 4481](https://www.adafruit.com/product/4481)), closest I have to a Nano 33 BLE.

The I2C scanner sketch ([from here](https://learn.adafruit.com/scanning-i2c-addresses/arduino)) reports both addresses:
![Screenshot from 2022-04-08 14-25-13](https://user-images.githubusercontent.com/8755041/162534915-04aca326-b81d-4143-9d69-3e4d5a23fedf.png)

The [MB85RC256V example](https://github.com/adafruit/Adafruit_FRAM_I2C/blob/master/examples/MB85RC256V/MB85RC256V.ino) from this library also runs as expected:
![Screenshot from 2022-04-08 14-28-59](https://user-images.githubusercontent.com/8755041/162534955-ed19e44b-16c2-4056-81e7-ccdb6f36fc91.png)

@dlveach Suggest posting in the forums with photos of your setup so we can look for any potential hardware issues:
https://forums.adafruit.com/

**Comment by dlveach** [comment]
I'll do that.   I have this all on a breadboard and I do have other I2C devices connected.   You made me think, I should try isolating the FRAM breakout alone without any other I2C devices and running Scanner before I do that.  Just in case there's some kind of interaction going on causing the secondary address not found.   Thank you.

**Comment by dlveach** [comment]
Posted.  https://forums.adafruit.com/viewtopic.php?f=22&t=190130

**Comment by dlveach** [comment]
Just following up to add that after discussion in the above post on the forums with "adafruit_support_mike", including some O-scope captures to confirm I2C comm is working, we confirmed the Adafruit board is just not responding to this secondary address check added in the 1.3.3 -> 2.0.0 library change.   Unless this change is rolled back it looks like I'm stuck on version 1.3.3 to continue using it.

**Comment by caternuson** [comment]
Closing. Can't recreate issue. Asked for additional information in forum thread linked above and still waiting response. Can reopen here if needed depending on how things play out in forum.

**Comment by jacob-newormics** [comment]
This same exact thing happened to me in my setup with the same product at the `i2c_dev` conditional even though it was showing up in a generic I2C scan. Reverting to 1.1.3 solved it.

Happy to try troubleshooting with you on this @caternuson
