### ISSUE TITLE
Adafruit Feather M0 (ATSAMD21) seems to work fine with Adafruit's I2C FRAM

### ISSUE THREAD

**Issue by bostrt** [adafruit/Adafruit_FRAM_I2C#3]
Hi!
I was sad to see that the Adafruit I2C FRAM breakout wasn't compatible with the Feather M0 (as indicated in the compatibility chart). However, I still tried it out just to see how it bad things break and it actually seems to work fine for me. I tried a couple lines from the example in this repo and it tracks restarts without issue.

Can you re-check on your side if the Feather M0 and FRAM breakout do actually work fine?

**Comment by ladyada** [comment]
its probably from when the SAMD core didn't support i2c repeated starts. and now it does? so, yay!

**Comment by ladyada** [comment]
clean up old issues
